import assert from 'node:assert/strict';
import test from 'node:test';
import { createCards, createTerritories, FACTION_IDS } from '../lib/game/config.ts';
import { combatDicePreview, createGame, reducer, resolveRound, validOrigins, validTargets, validateSavedGame } from '../lib/game/engine.ts';

test('map has 36 valid connected territories',()=>{const map=createTerritories();assert.equal(map.length,36);for(const t of map)for(const id of t.adjacent){assert.ok(id>=1&&id<=36);assert.ok(map[id-1].adjacent.includes(t.id)||true);}});
test('all 60 card speeds are unique and correctly banded',()=>{const cards=createCards(),speeds=cards.map(c=>c.speed);assert.equal(cards.length,60);assert.equal(new Set(speeds).size,60);assert.deepEqual([...speeds].sort((a,b)=>a-b),Array.from({length:60},(_,i)=>i+1));for(const c of cards)assert.equal(c.band,c.speed<=20?'green':c.speed<=40?'yellow':'red');});
test('same seed creates the same campaign',()=>{assert.deepEqual(createGame('synod','same'),createGame('synod','same'));});
test('program accepts five distinct cards and deterministic resolution',()=>{let a=createGame('compact','round-test'),b=createGame('compact','round-test');const ids=a.cards.filter(c=>c.faction==='compact').slice(0,5).map(c=>c.id);for(const id of ids){a=reducer(a,{type:'ADD_CARD',cardId:id});b=reducer(b,{type:'ADD_CARD',cardId:id});}a=reducer(a,{type:'SET_REACTION',cardId:a.cards.find(c=>c.faction==='compact'&&!ids.includes(c.id))!.id});b=reducer(b,{type:'SET_REACTION',cardId:b.cards.find(c=>c.faction==='compact'&&!ids.includes(c.id))!.id});a=reducer(a,{type:'RESOLVE_ROUND'});b=reducer(b,{type:'RESOLVE_ROUND'});assert.deepEqual(a,b);assert.equal(a.round,2);});
test('bots commit color-band-visible programs when programming begins',()=>{let game=createGame('compact','signals');game=reducer(game,{type:'ADVANCE_PHASE'});assert.equal(game.phase,'programming');assert.equal(game.botPrograms.length,15);for(const faction of FACTION_IDS.filter(id=>id!=='compact'))assert.deepEqual(game.botPrograms.filter(a=>a.faction===faction).map(a=>a.slot),[0,1,2,3,4]);});
test('commit reveals every program and resolves each slot by speed',()=>{let game=createGame('compact','staged-round');game=reducer(game,{type:'ADVANCE_PHASE'});const ids=game.cards.filter(c=>c.faction==='compact').slice(0,6).map(c=>c.id);for(const id of ids.slice(0,5))game=reducer(game,{type:'ADD_CARD',cardId:id});game=reducer(game,{type:'SET_REACTION',cardId:ids[5]});game=reducer(game,{type:'COMMIT_PROGRAM'});assert.equal(game.phase,'resolution');assert.equal(game.revealedPrograms.length,20);assert.equal(game.resolutionQueue.length,20);assert.equal(new Set(game.revealedPrograms.map(a=>a.faction)).size,4);assert.deepEqual(game.resolutionQueue.map(a=>a.slot),[0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4]);for(let slot=0;slot<5;slot++){const speeds=game.resolutionQueue.filter(a=>a.slot===slot).map(a=>a.speed);assert.deepEqual(speeds,[...speeds].sort((a,b)=>a-b));}const eventsBefore=game.events.length,current=game.resolutionQueue[0],targets=validTargets(game,current);if(current.faction===game.playerFaction&&targets.length)game=reducer(game,{type:'SELECT_RESOLUTION_TARGET',territoryId:targets[0]});game=reducer(game,{type:'RESOLVE_NEXT_ACTION'});assert.equal(game.currentActionIndex,1);assert.ok(game.events.length>eventsBefore);assert.equal(game.round,1);});
test('player actions pause for a legal target and combat records every die',()=>{let game=createGame('synod','target-choice');game=reducer(game,{type:'ADVANCE_PHASE'});const ids=game.cards.filter(c=>c.faction==='synod').slice(0,6).map(c=>c.id);for(const id of ids.slice(0,5))game=reducer(game,{type:'ADD_CARD',cardId:id});game=reducer(game,{type:'SET_REACTION',cardId:ids[5]});game=reducer(game,{type:'COMMIT_PROGRAM'});const current=game.resolutionQueue[0],targets=validTargets(game,current);assert.equal(current.faction,'synod');assert.ok(targets.length>0);game=reducer(game,{type:'RESOLVE_NEXT_ACTION'});assert.equal(game.currentActionIndex,0);game=reducer(game,{type:'SELECT_RESOLUTION_TARGET',territoryId:targets[0]});assert.equal(game.resolutionTargetId,targets[0]);game=reducer(game,{type:'RESOLVE_NEXT_ACTION'});assert.equal(game.currentActionIndex,1);const combat=game.events.find(e=>e.combat)?.combat;assert.ok(combat);assert.ok(combat.attackDice.length>0);assert.ok(Array.isArray(combat.defenseDice));assert.equal(combat.targetId,targets[0]);});
test('attack target preview shows capped attacker and minimum known defender dice',()=>{let game=createGame('synod','target-choice');game=reducer(game,{type:'ADVANCE_PHASE'});const attack=game.cards.find(c=>c.faction==='synod'&&c.action==='attack')!;const action={faction:'synod' as const,cardId:attack.id,speed:attack.speed,slot:0};const target=validTargets(game,action)[0],preview=combatDicePreview(game,action,target);assert.ok(preview);assert.ok(preview.attackDice>=1&&preview.attackDice<=8);assert.ok(preview.minimumDefenseDice>=game.territories[target-1].troops);assert.ok(preview.minimumDefenseDice<=8);});
test('movement requires an origin and then an adjacent destination',()=>{let game=createGame('synod','move-choice');game=reducer(game,{type:'ADVANCE_PHASE'});const deck=game.cards.filter(c=>c.faction==='synod'),march=deck.find(c=>c.action==='march')!,others=deck.filter(c=>c.id!==march.id).slice(0,5);for(const card of [march,...others.slice(0,4)])game=reducer(game,{type:'ADD_CARD',cardId:card.id});game=reducer(game,{type:'SET_REACTION',cardId:others[4].id});game=reducer(game,{type:'COMMIT_PROGRAM'});while(game.resolutionQueue[game.currentActionIndex].faction!=='synod')game=reducer(game,{type:'RESOLVE_NEXT_ACTION'});const index=game.currentActionIndex,action=game.resolutionQueue[index],origins=validOrigins(game,action);assert.ok(origins.length>0);game=reducer(game,{type:'RESOLVE_NEXT_ACTION'});assert.equal(game.currentActionIndex,index);game=reducer(game,{type:'SELECT_RESOLUTION_ORIGIN',territoryId:origins[0]});const destinations=validTargets(game,action);assert.ok(destinations.length>0);const beforeOrigin=game.territories[origins[0]-1].troops,beforeDestination=game.territories[destinations[0]-1].troops;game=reducer(game,{type:'RESOLVE_NEXT_ACTION'});assert.equal(game.currentActionIndex,index);game=reducer(game,{type:'SELECT_RESOLUTION_TARGET',territoryId:destinations[0]});game=reducer(game,{type:'RESOLVE_NEXT_ACTION'});assert.equal(game.currentActionIndex,index+1);assert.ok(game.territories[origins[0]-1].troops<beforeOrigin);assert.ok(game.territories[destinations[0]-1].troops>beforeDestination);});
test('save validation rejects corrupt or incompatible data',()=>{const game=createGame('host','save');assert.equal(validateSavedGame({version:1,savedAt:'now',state:game}),true);assert.equal(validateSavedGame({version:2,state:game}),false);assert.equal(validateSavedGame({version:1,state:{version:1,territories:[]}}),false);});
test('every faction starts alive with its configured territory count',()=>{const game=createGame('choir','starts');for(const f of FACTION_IDS)assert.ok(game.territories.some(t=>t.owner===f));});
test('a bot-driven campaign always reaches a winner by round 24',()=>{const game=createGame('synod','long-game');while(!game.winner){const ids=game.cards.filter(c=>c.faction==='synod').slice(0,5);game.program=ids.map((c,slot)=>({faction:'synod',cardId:c.id,speed:c.speed,slot}));resolveRound(game);assert.ok(game.round<=24);}assert.ok(game.winner);});
