'use client';

import { useEffect, useState } from 'react';
import { Eye, Hammer, RotateCcw, ScrollText, Shield, Sparkles, Swords, Target, X } from 'lucide-react';
import { FACTIONS, FACTION_IDS, REGION_NAMES, ROLES } from '@/lib/game/config';
import { createGame, reducer, resolveRound, validateSavedGame } from '@/lib/game/engine';
import type { CardDefinition, FactionId, GameState, RoleId, SavedGame } from '@/lib/game/types';

const SAVE_KEY='nox-certamen-save-v1';
const actionIcon:Record<string,typeof Swords>={attack:Swords,repair:Hammer,fortify:Shield,recon:Eye,sabotage:Target,develop:Sparkles,march:ScrollText,faction:Sparkles};

function Setup({onStart,onResume,hasSave}:{onStart:(f:FactionId,s:string)=>void;onResume:()=>void;hasSave:boolean}){
  const[faction,setFaction]=useState<FactionId>('synod');const[seed,setSeed]=useState('NOX-1703');
  return <main className="setup-shell"><header className="setup-header"><div className="brand-mark"><span>NC</span></div><div><p className="eyebrow">Field prototype 0.1</p><h1>Nox Certamen</h1></div></header><section className="setup-grid"><div className="setup-copy"><p className="kicker">The Shattered Marches await</p><h2>Program the war.<br/><i>Survive the reveal.</i></h2><p>Choose your covenant, conceal its infrastructure, then commit five orders while three rival powers plot in the dark.</p><div className="rule-pills"><span>36 territories</span><span>5 hidden orders</span><span>10 VP to win</span></div></div><div className="setup-card panel"><p className="eyebrow">Choose your covenant</p><div className="faction-list">{FACTION_IDS.map(id=>{const f=FACTIONS[id];return <button key={id} className={faction===id?'faction active':'faction'} onClick={()=>setFaction(id)}><span className="sigil" style={{background:f.color}}/><span><strong>{f.name}</strong><small>{f.startTerritories} territories · {f.production} production</small></span><b>DEF +{f.defenseBonus}</b></button>})}</div><div className="faction-lore"><strong>{FACTIONS[faction].special.split(' — ')[0]}</strong><span>{FACTIONS[faction].special.split(' — ')[1]}</span></div><label className="seed-label">Campaign seed<input value={seed} onChange={e=>setSeed(e.target.value||'NOX')}/></label><button className="primary" onClick={()=>onStart(faction,seed)}>Begin campaign</button>{hasSave&&<button className="secondary" onClick={onResume}>Resume saved campaign</button>}</div></section><div className="phone-notice">Nox Certamen needs a tablet or desktop-sized screen for its command map.</div></main>
}

function Map({game,onSelect}:{game:GameState;onSelect:(id:number)=>void}){
  const player=game.playerFaction;return <section className="map-panel panel"><div className="map-heading"><div><p className="eyebrow">The Shattered Marches</p><h2>{REGION_NAMES[game.territories[game.selectedTerritory?game.selectedTerritory-1:0].region]}</h2></div><div className="legend"><span>◈ HQ</span><span>◆ Role</span><span>● Troops</span></div></div><svg viewBox="0 0 860 590" role="img" aria-label="Interactive map of 36 territories">{game.territories.flatMap(t=>t.adjacent.filter(id=>id>t.id).map(id=><line key={`${t.id}-${id}`} x1={t.x} y1={t.y} x2={game.territories[id-1].x} y2={game.territories[id-1].y} className="route"/>))}{game.territories.map(t=>{const f=t.owner?game.factions[t.owner]:null;const selected=game.selectedTerritory===t.id;const visible=t.owner===player||t.roleRevealed;return <g key={t.id} className={`territory ${selected?'selected':''}`} role="button" tabIndex={0} aria-label={`${t.name}, ${t.troops} troops`} onClick={()=>onSelect(t.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onSelect(t.id)}}><circle cx={t.x} cy={t.y} r="27" fill={f?.color??'#30343a'}/><circle cx={t.x} cy={t.y} r="20" className="inner"/><text x={t.x} y={t.y+4} className="troops">{t.troops}</text>{visible&&t.role==='hq'&&<text x={t.x+20} y={t.y-18} className="role-mark">◈</text>}{visible&&t.role&&t.role!=='hq'&&<text x={t.x+20} y={t.y-18} className="role-mark">◆</text>}{t.damage>0&&<text x={t.x-27} y={t.y-20} className="damage">-{t.damage}</text>}<text x={t.x} y={t.y+41} className="territory-name">{t.name}</text></g>})}</svg><div className="map-footer"><span>Select a territory before adding an Attack card to focus its target.</span><span>Round {game.round}</span></div></section>
}

function Card({card,chosen,reaction,onAdd,onReact}:{card:CardDefinition;chosen:boolean;reaction:boolean;onAdd:()=>void;onReact:()=>void}){const Icon=actionIcon[card.action]??ScrollText;return <article className={`order-card ${card.band} ${chosen?'chosen':''}`}><div className="card-speed"><span>{card.speed}</span><small>{card.band}</small></div><Icon size={18}/><strong>{card.name}</strong><p>{card.sequence}</p><div className="card-actions"><button onClick={onAdd} disabled={chosen}>{chosen?'Queued':'Sequence'}</button><button onClick={onReact} className={reaction?'reaction-active':''}>Reaction</button></div></article>}

function Game({initial,onExit}:{initial:GameState;onExit:()=>void}){
  const[game,setGame]=useState(initial);const[showRules,setShowRules]=useState(false);const[playerPanel,setPlayerPanel]=useState<'cards'|'objectives'|'tech'>('cards');
  useEffect(()=>{const save:SavedGame={version:1,savedAt:new Date().toISOString(),state:game};localStorage.setItem(SAVE_KEY,JSON.stringify(save));},[game]);
  const act=(command:Parameters<typeof reducer>[1])=>setGame(g=>reducer(g,command));
  const player=game.factions[game.playerFaction],selected=game.selectedTerritory?game.territories[game.selectedTerritory-1]:null;
  const deck=game.cards.filter(c=>c.faction===game.playerFaction);const lastCombat=game.events.find(e=>e.combat)?.combat;
  const setRole=(role:RoleId)=>{if(!selected||selected.owner!==game.playerFaction||game.phase!=='production')return;setGame(g=>{const n=structuredClone(g);n.territories[selected.id-1].role=role;n.territories[selected.id-1].roleRevealed=true;return n;});};
  const buyTech=(id:string,cost:number)=>{if(player.intel<cost||player.technologies.includes(id))return;setGame(g=>{const n=structuredClone(g);n.factions[n.playerFaction].intel-=cost;n.factions[n.playerFaction].technologies.push(id);n.events.unshift({id:(n.events[0]?.id??0)+1,round:n.round,type:'technology',message:`${n.factions[n.playerFaction].name} researches ${n.technologies.find(t=>t.id===id)?.name}.`});return n;});};
  const removeCard=(id:string)=>act({type:'REMOVE_CARD',cardId:id});
  const resolve=()=>setGame(g=>{const n=structuredClone(g);resolveRound(n);return n;});
  return <main className="game-shell"><header className="topbar"><div className="brand-mark"><span>NC</span></div><div><p className="eyebrow">Solo field prototype</p><h1>Nox Certamen</h1></div><div className="round-track"><span className={game.phase==='production'?'on':''}>Production</span><i>›</i><span className={game.phase==='programming'?'on':''}>Program</span><i>›</i><span className={game.phase==='resolution'?'on':''}>Resolve</span></div><button className="icon-button" aria-label="Open rules" onClick={()=>setShowRules(true)}>?</button><button className="icon-button" aria-label="New game" onClick={onExit}><RotateCcw size={16}/></button></header>
    <section className="workspace"><aside className="left-rail"><section className="panel commander"><p className="eyebrow">Your covenant</p><div className="commander-name"><span style={{background:player.color}}>{player.glyph}</span><div><h3>{player.name}</h3><small>{player.special}</small></div></div><div className="meter"><span>Victory</span><strong>{player.vp} / 10 VP</strong><i><b style={{width:`${player.vp*10}%`}}/></i></div><div className="resource-row"><div><small>Intel</small><strong>{player.intel}</strong></div><div><small>Round</small><strong>{game.round}</strong></div><div><small>Lands</small><strong>{game.territories.filter(t=>t.owner===game.playerFaction).length}</strong></div></div></section>
    <section className="panel territory-detail"><p className="eyebrow">Territory dossier</p>{selected?<><h3>{selected.name}</h3><p className="owner-line"><span style={{background:selected.owner?game.factions[selected.owner].color:'#555'}}/>{selected.owner?game.factions[selected.owner].name:'Neutral'}</p><dl><div><dt>Troops</dt><dd>{selected.troops}</dd></div><div><dt>Defense</dt><dd>{selected.defense}</dd></div><div><dt>Damage</dt><dd>{selected.damage}</dd></div><div><dt>Links</dt><dd>{selected.adjacent.length}</dd></div></dl>{selected.owner===game.playerFaction&&game.phase==='production'?<label className="role-select">Secret role<select value={selected.role??'depot'} onChange={e=>setRole(e.target.value as RoleId)}>{ROLES.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>:<p className="role-readout">{selected.roleRevealed||selected.owner===game.playerFaction?(ROLES.find(r=>r.id===selected.role)?.name??'No infrastructure'):'Hidden infrastructure'}</p>}</>:<p className="muted">Select a territory on the map.</p>}</section>
    <section className="panel rivals"><p className="eyebrow">Rival powers</p>{FACTION_IDS.filter(f=>f!==game.playerFaction).map(id=>{const f=game.factions[id];return <div className={f.eliminated?'rival eliminated':'rival'} key={id}><span style={{background:f.color}}/><div><strong>{f.name}</strong><small>{f.eliminated?'Eliminated':`${f.vp} VP · ${game.territories.filter(t=>t.owner===id).length} lands`}</small></div></div>})}</section></aside>
    <Map game={game} onSelect={id=>act({type:'SELECT_TERRITORY',territoryId:id})}/>
    <aside className="right-rail"><section className="panel tabs"><div className="tab-list"><button className={playerPanel==='cards'?'active':''} onClick={()=>setPlayerPanel('cards')}>Orders</button><button className={playerPanel==='objectives'?'active':''} onClick={()=>setPlayerPanel('objectives')}>VP</button><button className={playerPanel==='tech'?'active':''} onClick={()=>setPlayerPanel('tech')}>Tech</button></div>{playerPanel==='cards'?<><p className="helper">Select five Sequence cards. Your selected map territory becomes an Attack focus.</p><div className="mini-deck">{deck.map(card=><Card key={card.id} card={card} chosen={game.program.some(a=>a.cardId===card.id)} reaction={game.reaction?.cardId===card.id} onAdd={()=>act({type:'ADD_CARD',cardId:card.id})} onReact={()=>act({type:'SET_REACTION',cardId:card.id})}/>)}</div></>:playerPanel==='objectives'?<div className="objective-list"><p className="eyebrow">Public claims</p>{game.publicObjectives.map(o=><article key={o.id}><strong>{o.name}<b>{o.vp} VP</b></strong><p>{o.description}</p></article>)}<p className="eyebrow secret-label">Secret purpose</p><article className="secret-objective"><strong>{game.factions[game.playerFaction].secretObjective}</strong><p>Known only to your covenant. Complete it before your rivals read your design.</p></article></div>:<div className="tech-list">{game.technologies.map(t=><article key={t.id}><div><strong>{t.name}</strong><p>{t.description}</p></div><button disabled={player.intel<t.cost||player.technologies.includes(t.id)} onClick={()=>buyTech(t.id,t.cost)}>{player.technologies.includes(t.id)?'Known':`${t.cost} intel`}</button></article>)}</div>}</section></aside></section>
    <section className="command-dock"><div className="queue"><p className="eyebrow">Program queue</p><div>{[0,1,2,3,4].map(i=>{const action=game.program[i],card=action?game.cards.find(c=>c.id===action.cardId):null;return <button key={i} className={card?`queue-card ${card.band}`:'queue-card empty'} onClick={()=>card&&removeCard(card.id)}><span>{i+1}</span>{card?<><strong>{card.name}</strong><small>Speed {card.speed}</small><X size={13}/></>:<em>Empty</em>}</button>})}</div></div><div className="reaction-display"><p className="eyebrow">Hidden reaction</p><strong>{game.reaction?game.cards.find(c=>c.id===game.reaction?.cardId)?.name:'Choose a card'}</strong></div>{game.phase==='production'?<button className="resolve-button" onClick={()=>act({type:'ADVANCE_PHASE'})}>Lock roles & program</button>:<button className="resolve-button" disabled={game.program.length!==5||!game.reaction} onClick={resolve}>Reveal & resolve <small>{game.program.length}/5 orders</small></button>}</section>
    <section className="field-log panel"><div className="log-head"><p className="eyebrow">Field log</p>{lastCombat&&<div className="dice-summary"><span>{lastCombat.attackDice.join(' ')}</span><i>vs</i><span>{lastCombat.defenseDice.join(' ')}</span></div>}</div><div className="log-scroll">{game.events.slice(0,18).map(e=><p key={e.id}><time>R{e.round}</time><span className={`event-dot ${e.type}`}/>{e.message}</p>)}</div></section>
    {game.winner&&<div className="modal-backdrop"><section className="victory panel"><p className="eyebrow">The contest is decided</p><h2>{game.factions[game.winner].name} reigns</h2><p>{game.winner===game.playerFaction?'The Marches answer to your hidden design.':'Your covenant is scattered, but the seed remains for another campaign.'}</p><button className="primary" onClick={onExit}>Begin another campaign</button></section></div>}
    {showRules&&<div className="modal-backdrop" onClick={()=>setShowRules(false)}><section className="rules panel" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowRules(false)}><X/></button><p className="eyebrow">Combat quick reference</p><h2>One exchange decides the assault.</h2><ol><li>Attack cards launch up to two orders; adjacent origins may combine.</li><li>Roll committed troops plus bonuses against defenders × terrain plus bonuses. Each pool caps at 8d6.</li><li>Sort high to low. Higher paired die removes a troop.</li><li>A tie strips one non-troop defense bonus and adds persistent damage. With no bonus left, defender wins ties.</li><li>Capture moves surviving attackers in. Failed attackers return home.</li></ol><p>Green Repair removes 1 damage, Yellow removes 2, and Red clears one territory.</p></section></div>}
    <div className="phone-notice">Nox Certamen needs a tablet or desktop-sized screen for its command map.</div></main>
}

export default function Home(){
  const[game,setGame]=useState<GameState|null>(null);const[hasSave,setHasSave]=useState(false);
  useEffect(()=>{queueMicrotask(()=>setHasSave(Boolean(localStorage.getItem(SAVE_KEY))));},[]);
  useEffect(()=>{
    type Tool={name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
    const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tool:Tool={name:'start_nox_campaign',title:'Start Nox Certamen campaign',description:'Start a visible solo Nox Certamen campaign with one human faction and three bots.',inputSchema:{type:'object',properties:{faction:{type:'string',enum:FACTION_IDS},seed:{type:'string',minLength:1}},required:['faction','seed'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=input as {faction?:FactionId;seed?:string};if(!value||!FACTION_IDS.includes(value.faction as FactionId)||typeof value.seed!=='string'||!value.seed.trim())throw new Error('A valid faction and non-empty seed are required.');const next=createGame(value.faction as FactionId,value.seed.trim());setGame(next);return{status:'started',faction:next.factions[next.playerFaction].name,seed:next.seed,round:next.round};}};
    try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined);}catch{/* WebMCP is optional in unsupported browsers. */}return()=>lifecycle.abort();
  },[]);
  const resume=()=>{try{const parsed=JSON.parse(localStorage.getItem(SAVE_KEY)??'null');if(validateSavedGame(parsed))setGame(parsed.state);else{localStorage.removeItem(SAVE_KEY);setHasSave(false);}}catch{localStorage.removeItem(SAVE_KEY);setHasSave(false);}};
  const exit=()=>{localStorage.removeItem(SAVE_KEY);setGame(null);setHasSave(false);};
  return game?<Game initial={game} onExit={exit}/>:<Setup hasSave={hasSave} onResume={resume} onStart={(f,s)=>setGame(createGame(f,s))}/>;
}
