import { createCards, createTerritories, FACTIONS, FACTION_IDS, PUBLIC_OBJECTIVES, ROLES, SECRET_OBJECTIVES, TECHNOLOGIES } from './config.ts';
import { hashSeed, nextRandom, rollDie } from './rng.ts';
import type { BotDecision, CombatResult, FactionId, GameCommand, GameState, ProgrammedAction, Territory } from './types.ts';

const clone=<T,>(v:T):T=>structuredClone(v);
function event(state:GameState,type:string,message:string,combat?:CombatResult){state.events.unshift({id:(state.events[0]?.id??0)+1,round:state.round,type,message,combat});state.events=state.events.slice(0,120);}
function shuffle<T>(items:T[],state:number):[T[],number]{const out=[...items];for(let i=out.length-1;i>0;i--){const[r,s]=nextRandom(state);state=s;const j=Math.floor(r*(i+1));[out[i],out[j]]=[out[j],out[i]];}return[out,state];}
function owned(state:GameState,f:FactionId){return state.territories.filter(t=>t.owner===f);}
function border(state:GameState,f:FactionId){return owned(state,f).filter(t=>t.adjacent.some(id=>state.territories[id-1].owner!==f));}
function techBonus(state:GameState,f:FactionId,key:'attackBonus'|'defenseBonus'|'productionBonus'){return state.factions[f].technologies.reduce((n,id)=>n+(TECHNOLOGIES.find(t=>t.id===id)?.[key]??0),0);}

export function createGame(playerFaction:FactionId,seed:string):GameState{
  let rngState=hashSeed(seed);const territories=createTerritories();
  const factions=Object.fromEntries(FACTION_IDS.map(id=>[id,{...FACTIONS[id],vp:0,intel:0,eliminated:false,technologies:[],secretObjective:SECRET_OBJECTIVES[FACTION_IDS.indexOf(id)%SECRET_OBJECTIVES.length].id}])) as unknown as GameState['factions'];
  const starts:Record<FactionId,number[]>={synod:[1,2,7,8],compact:[5,6,11,12,17],host:[19,20,25,26,31,32],choir:[23,24,29,30,34,35,36]};
  for(const f of FACTION_IDS){const roleOrder=['hq','industrial','warehouse','spy','training','fortress','depot'] as const;starts[f].forEach((id,i)=>{territories[id-1].owner=f;territories[id-1].troops=i===0?4:2;territories[id-1].role=roleOrder[i%roleOrder.length];territories[id-1].roleRevealed=f===playerFaction;});}
  const[deck,next]=shuffle(PUBLIC_OBJECTIVES,rngState);rngState=next;
  const state:GameState={version:1,seed,rngState,round:1,phase:'production',playerFaction,factions,territories,cards:createCards(),program:[],revealedPrograms:[],resolutionQueue:[],currentActionIndex:0,reaction:null,events:[],publicObjectives:deck.slice(0,3),objectiveDeck:deck.slice(3),technologies:TECHNOLOGIES,winner:null,selectedTerritory:null};
  production(state);event(state,'campaign',`${factions[playerFaction].name} enters the Shattered Marches.`);return state;
}

export function production(state:GameState){for(const f of FACTION_IDS){if(state.factions[f].eliminated)continue;const lands=owned(state,f);const industrial=lands.find(t=>t.role==='industrial')??lands[0];if(!industrial)continue;const amount=state.factions[f].production+techBonus(state,f,'productionBonus');industrial.troops+=amount;if(lands.some(t=>t.role==='spy'))state.factions[f].intel+=1;event(state,'production',`${state.factions[f].name} musters ${amount} at ${industrial.name}.`);}}
function rollPool(count:number,state:GameState){const dice:number[]=[];for(let i=0;i<Math.min(8,Math.max(0,count));i++){const[d,s]=rollDie(state.rngState);state.rngState=s;dice.push(d);}return dice.sort((a,b)=>b-a);}
function resolveCombat(state:GameState,attacker:FactionId,target:Territory,origins:Territory[],attackBonus=0):CombatResult{
  const defender=target.owner;const committed=origins.map(o=>Math.max(1,Math.min(o.troops-1,Math.ceil((o.troops-1)*.65))));
  const attackCount=committed.reduce((a,b)=>a+b,0)+attackBonus+techBonus(state,attacker,'attackBonus')+(origins.some(o=>o.role==='training')?state.factions[attacker].trainingBonus:0);
  const roleBonus=ROLES.find(r=>r.id===target.role)?.defenseBonus??0;
  const rawBonus=target.troops*(target.defense-1)+(defender?state.factions[defender].defenseBonus+techBonus(state,defender,'defenseBonus'):0)+roleBonus+target.fortified;
  const activeBonus=Math.max(0,Math.min(8-Math.min(8,target.troops),rawBonus)-target.damage);
  const attackDice=rollPool(attackCount,state),defenseDice=rollPool(target.troops+activeBonus,state);
  let attackerLosses=0,defenderLosses=0,damageAdded=0,remainingBonus=activeBonus;
  for(let i=0;i<Math.min(attackDice.length,defenseDice.length);i++){
    if(attackDice[i]>defenseDice[i]&&defenderLosses<target.troops)defenderLosses++;
    else if(attackDice[i]<defenseDice[i]&&attackerLosses<committed.reduce((a,b)=>a+b,0))attackerLosses++;
    else if(remainingBonus>0){remainingBonus--;damageAdded++;}
    else if(attackerLosses<committed.reduce((a,b)=>a+b,0))attackerLosses++;
  }
  target.troops-=defenderLosses;target.damage+=damageAdded;let losses=attackerLosses;
  origins.forEach((o,i)=>{const take=Math.min(committed[i],losses);o.troops-=take;committed[i]-=take;losses-=take;});
  let captured=false;if(target.troops<=0&&committed.some(n=>n>0)){const oldRole=target.role;captured=true;target.owner=attacker;target.troops=committed.reduce((a,b)=>a+b,0);origins.forEach((o,i)=>o.troops-=committed[i]);target.role=null;target.roleRevealed=false;target.fortified=0;if(oldRole==='hq'&&defender){state.factions[defender].eliminated=true;state.factions[attacker].vp+=3;for(const t of state.territories.filter(t=>t.owner===defender)){t.owner=null;t.troops=1;t.role=null;t.roleRevealed=false;}event(state,'elimination',`${state.factions[defender].name} falls with its hidden HQ.`);}}
  else origins.forEach((o,i)=>{void i;});
  target.roleRevealed=true;
  const summary=`${state.factions[attacker].name} ${captured?'captures':'assaults'} ${target.name}: ${attackerLosses} attacker and ${defenderLosses} defender losses${damageAdded?`, ${damageAdded} defense damage`:''}.`;
  return{attacker,defender,targetId:target.id,originIds:origins.map(o=>o.id),attackDice,defenseDice,attackerLosses,defenderLosses,damageAdded,captured,summary};
}
function chooseTarget(state:GameState,f:FactionId,preferred?:number){const candidates=border(state,f).flatMap(o=>o.adjacent.map(id=>({o,t:state.territories[id-1]})).filter(x=>x.t.owner!==f&&o.troops>1));if(!candidates.length)return null;const preferredHit=candidates.find(x=>x.t.id===preferred);if(preferredHit)return preferredHit;candidates.sort((a,b)=>(a.t.troops+a.t.damage)-(b.t.troops+b.t.damage)||b.o.troops-a.o.troops);const top=candidates.slice(0,Math.min(3,candidates.length));const[r,s]=nextRandom(state.rngState);state.rngState=s;return top[Math.floor(r*top.length)];}
function execute(state:GameState,a:ProgrammedAction){const card=state.cards.find(c=>c.id===a.cardId)!;const faction=a.faction;if(state.factions[faction].eliminated)return;
  if(card.action==='attack'){const first=chooseTarget(state,faction,a.targetId);if(!first){event(state,'fallback',`${state.factions[faction].name}'s ${card.name} becomes a fortified hold.`);const home=border(state,faction)[0];if(home)home.fortified++;return;}const sameTargetOrigins=border(state,faction).filter(o=>o.troops>1&&o.adjacent.includes(first.t.id)).sort((a,b)=>b.troops-a.troops).slice(0,2);first.t.roleRevealed=true;const result=resolveCombat(state,faction,first.t,sameTargetOrigins,card.power-1);event(state,'combat',result.summary,result);}
  else if(card.action==='repair'){const target=owned(state,faction).filter(t=>t.damage>0).sort((a,b)=>b.damage-a.damage)[0];if(target){const amount=card.band==='green'?1:card.band==='yellow'?2:target.damage;target.damage=Math.max(0,target.damage-amount);event(state,'repair',`${state.factions[faction].name} repairs ${amount} damage at ${target.name}.`);}else event(state,'fallback',`${card.name} becomes a hold; no damaged supplied territory exists.`);}
  else if(card.action==='fortify'){const target=border(state,faction).sort((a,b)=>a.troops-b.troops)[0];if(target){target.fortified=Math.min(2,target.fortified+card.power);event(state,'fortify',`${state.factions[faction].name} fortifies ${target.name}.`);}}
  else if(card.action==='develop'){const target=owned(state,faction).sort((a,b)=>a.troops-b.troops)[0];if(target){target.troops+=card.power+(faction==='choir'?1:0);event(state,'develop',`${state.factions[faction].name} raises ${card.power+(faction==='choir'?1:0)} troops at ${target.name}.`);}}
  else if(card.action==='recon'){state.factions[faction].intel++;const enemy=border(state,faction).flatMap(t=>t.adjacent.map(id=>state.territories[id-1])).find(t=>t.owner!==faction&&!t.roleRevealed);if(enemy)enemy.roleRevealed=true;event(state,'recon',`${state.factions[faction].name} gains intel${enemy?` and reveals ${enemy.name}`:''}.`);}
  else if(card.action==='sabotage'){const hit=chooseTarget(state,faction);if(hit){hit.t.damage++;event(state,'sabotage',`${state.factions[faction].name} sabotages ${hit.t.name}.`);}}
  else {const from=owned(state,faction).sort((a,b)=>b.troops-a.troops)[0],to=from?.adjacent.map(id=>state.territories[id-1]).find(t=>t.owner===faction&&t.troops<from.troops);if(from&&to&&from.troops>1){const moved=Math.min(card.power,from.troops-1);from.troops-=moved;to.troops+=moved;event(state,'march',`${state.factions[faction].name} marches ${moved} troops to ${to.name}.`);}}
}
export function botDecision(state:GameState,faction:FactionId):BotDecision{const deck=state.cards.filter(c=>c.faction===faction);const damaged=owned(state,faction).some(t=>t.damage>0);const borders=border(state,faction);const scored=deck.map(c=>({c,score:(c.action==='attack'?borders.length*2:0)+(c.action==='repair'&&damaged?7:0)+(c.action==='fortify'?3:0)+(c.action==='develop'?2:0)+c.power})).sort((a,b)=>b.score-a.score);const pool=scored.slice(0,9);const picks:string[]=[];while(picks.length<5&&pool.length){const[r,s]=nextRandom(state.rngState);state.rngState=s;const idx=Math.floor(r*Math.min(4,pool.length));picks.push(pool.splice(idx,1)[0].c.id);}const reaction=deck.find(c=>!picks.includes(c.id))!;return{faction,cardIds:picks,reactionId:reaction.id,score:scored[0]?.score??0,reason:damaged?'Balances repair with pressure.':'Weights borders, development, and defense.'};}
function claimObjectives(state:GameState){for(const f of FACTION_IDS){if(state.factions[f].eliminated)continue;const regions=new Set(owned(state,f).map(t=>t.region));const captures=state.events.filter(e=>e.round===state.round&&e.combat?.attacker===f&&e.combat.captured).length;const hit=state.publicObjectives.find(o=>(o.id==='breaker'&&captures>=2)||(o.id==='dominion'&&[...regions].some(r=>state.territories.filter(t=>t.region===r).every(t=>t.owner===f)))||(o.id==='siege'&&state.events.some(e=>e.round===state.round&&e.combat?.attacker===f&&e.combat.captured&&state.territories[e.combat.targetId-1].damage>0)));
    if(hit){state.factions[f].vp+=hit.vp;event(state,'objective',`${state.factions[f].name} claims ${hit.name} for ${hit.vp} VP.`);state.publicObjectives=state.publicObjectives.filter(o=>o.id!==hit.id);const next=state.objectiveDeck.shift();if(next)state.publicObjectives.push(next);}}
}
export function commitPrograms(state:GameState){if(state.phase==='resolution'||state.program.length!==5)return;const all=[...state.program];for(const f of FACTION_IDS.filter(f=>f!==state.playerFaction&&!state.factions[f].eliminated)){const d=botDecision(state,f);for(const id of d.cardIds){const c=state.cards.find(c=>c.id===id)!;all.push({faction:f,cardId:id,speed:c.speed});}event(state,'bot',`${state.factions[f].name}: ${d.reason}`);}state.revealedPrograms=[...all];state.resolutionQueue=[...all].sort((a,b)=>a.speed-b.speed);state.currentActionIndex=0;state.phase='resolution';event(state,'reveal',`All ${all.length} programmed orders are revealed. Resolve them from lowest to highest Speed.`);}
function finishRound(state:GameState){claimObjectives(state);let winner=FACTION_IDS.find(f=>state.factions[f].vp>=10)||((FACTION_IDS.filter(f=>!state.factions[f].eliminated).length===1)?FACTION_IDS.find(f=>!state.factions[f].eliminated):undefined);if(!winner&&state.round>=24)winner=[...FACTION_IDS].filter(f=>!state.factions[f].eliminated).sort((a,b)=>state.factions[b].vp-state.factions[a].vp||owned(state,b).length-owned(state,a).length||owned(state,b).reduce((n,t)=>n+t.troops,0)-owned(state,a).reduce((n,t)=>n+t.troops,0))[0];if(winner){state.winner=winner;state.phase='ended';event(state,'victory',`${state.factions[winner].name} wins the Nox Certamen.`);return;}state.round++;state.program=[];state.reaction=null;state.revealedPrograms=[];state.resolutionQueue=[];state.currentActionIndex=0;state.phase='production';production(state);state.phase='programming';}
export function resolveNextAction(state:GameState){if(state.phase!=='resolution')return;const action=state.resolutionQueue[state.currentActionIndex];if(!action){finishRound(state);return;}const card=state.cards.find(c=>c.id===action.cardId)!;event(state,'resolution',`Resolving ${state.factions[action.faction].name}'s ${card.name} at Speed ${card.speed}.`);execute(state,action);state.currentActionIndex++;}
export function resolveRound(state:GameState){if(state.phase!=='resolution')commitPrograms(state);while(state.phase==='resolution')resolveNextAction(state);}
export function reducer(state:GameState,command:GameCommand):GameState{if(command.type==='START')return createGame(command.faction,command.seed);if(command.type==='RESET')return state;const next=clone(state);if(command.type==='SELECT_TERRITORY')next.selectedTerritory=command.territoryId;if(command.type==='ADD_CARD'&&next.phase!=='resolution'&&next.program.length<5&&!next.program.some(a=>a.cardId===command.cardId)){const c=next.cards.find(c=>c.id===command.cardId)!;next.program.push({faction:next.playerFaction,cardId:c.id,speed:c.speed,targetId:next.selectedTerritory??undefined});next.phase='programming';}if(command.type==='REMOVE_CARD'&&next.phase!=='resolution')next.program=next.program.filter(a=>a.cardId!==command.cardId);if(command.type==='SET_REACTION'&&next.phase!=='resolution')next.reaction={faction:next.playerFaction,cardId:command.cardId,trigger:'attacked',used:false};if(command.type==='COMMIT_PROGRAM'&&next.program.length===5&&next.reaction)commitPrograms(next);if(command.type==='RESOLVE_NEXT_ACTION')resolveNextAction(next);if(command.type==='RESOLVE_ROUND'&&next.program.length===5)resolveRound(next);if(command.type==='ADVANCE_PHASE')next.phase='programming';return next;}
export function validateSavedGame(value:unknown):value is {version:1;savedAt:string;state:GameState}{if(!value||typeof value!=='object')return false;const v=value as {version?:unknown;state?:{version?:unknown;territories?:unknown;revealedPrograms?:unknown;resolutionQueue?:unknown;currentActionIndex?:unknown}};return v.version===1&&v.state?.version===1&&Array.isArray(v.state.territories)&&v.state.territories.length===36&&Array.isArray(v.state.revealedPrograms)&&Array.isArray(v.state.resolutionQueue)&&typeof v.state.currentActionIndex==='number';}
